### ISSUE TITLE
Several formatting types in a cell

### ISSUE THREAD

**Issue by Arthfael** [ycphs/openxlsx#98] opened 2020-08-29 09:44 UTC
Please forgive me if this is already possible, but I could not find a way to do this using this otherwise excellent package (or others).
Is it possible to create different formatting within a single cell? For instance, in Excel, in a cell with a sentence, I could set specific words rather than the whole sentence to be bold, underlined, or in a different colour. Is this something I have to do by inserting some kind of html/xml codes in the text within the cell, or can this be achieved using this package? I could for instance identify positions in the sentence matching words of interest, or (in my precise case) regions of a protein sequence which were observed in the experiment, and apply a specific formatting to them.
Again my apologies if this is a duplicate...

**Comment by FolkyHobbit** [comment] 2021-08-20 12:59
Duplicate of  #46

**Closed as completed** 2021-09-25 17:30 UTC
Labels: enhancement, Style issue
