### ISSUE TITLE
NAs generated by creation of xlsx-document

### ISSUE THREAD

**Issue by dkoltg** [ycphs/openxlsx#349] opened 2022-05-05 07:41 UTC
**Describe the bug**
Since a few days, I have problems when writing the created wb as an xlsx-file. There appears the error message: NAs are created by conversion. I removed all NAs in both file that are used for the wb. Therefore, I have no clue where there error comes from so recently.

**To Reproduce**
```R
## Create a new workbook
library(openxlsx)
wb <- createWorkbook("Full")

## Add some worksheets
addWorksheet(wb, "File_1")
addWorksheet(wb, "File_2")

hs1 <- createStyle(halign = "LEFT", wrapText = TRUE, valign = "TOP")

writeData(wb, "File_1", tab_file_1, colNames = T, rowNames = F,  headerStyle = hs1)
writeData(wb, "File_2", tab_file_2, colNames = T, rowNames = F,  headerStyle = hs1)
setColWidths(wb, "File_1",col=1,widths = "auto")
setColWidths(wb, "File_2",col=1,widths = "auto")
setColWidths(wb, "File_1",cols=2:4,widths=10)
setColWidths(wb, "File_2",cols=2:4,widths=11)
setColWidths(wb, "File_2",cols=5:6,widths=12)

## Freeze Panes
freezePane(wb, "File_1", firstRow = TRUE)
freezePane(wb, "File_2", firstRow = TRUE)

## Save workbook
saveWorkbook(wb, "~path/full.xlsx", 
             overwrite = TRUE)
```

**Expected behavior**

**Screenshots**
Error: 
![image](https://user-images.githubusercontent.com/35335511/166880843-6439c398-0b88-4c46-997c-03ae70371a9f.png)

**Comment by JanMarvin** [comment] 2022-05-12 16:38
Hi @dkoltg , I've edited your snipped above (just enabled markdown). Is your path correct? That looks like it is missing a slash, otherwise your code -- replacing `tab_file_1` and `tab_file_2` with `mtcars` -- runs without any warning for me. Maybe the issue is in your data? Where exactly do you see the warning?

**Comment by dkoltg** [comment] 2022-05-13 05:44
Hi @JanMarvin, thanks for your reply. After writing the comment, I played around a bit more with the code and as soon as I removed the parts setColWidths the warnings disappeared. I reproduced the whole chunk this morning including setColWidth and had - as you - no warnings - without having changed anything in one case. However in the other case, the warnings remain and the first column (including dates from May 2021 to yestersdays date without any missing dates between start and end date) disappears in the produced xlsx-file and the warning that NA through convertion are generated remains.

**Comment by JanMarvin** [comment] 2022-05-13 07:25
Alright, we're always happy to ... err ... help 😄

**Comment by dkoltg** [comment] 2022-05-13 08:17
Any other idea how to solve the issue with the setColWidth in the second case? see comment above

**Comment by JanMarvin** [comment] 2022-05-13 08:31
Ah sorry, you must have edited it while I closed it. Could you try to replicate the warning with some artifical data somehow? It's a bit hard to imagine what your data looks like and if you can not reproduce it, I would have to.

**Comment by dkoltg** [comment] 2022-05-13 08:42
Sorry, I did edit the comment because I have seen the warnings in the second case just after posting the first version.
The warnings are the same as in the first comment. The file for the wb are to tables with the first column as character (date in Swiss format %d.%m.%Y) and 4 (6 columns respectively) with numbers. So nothing very special, as I see it...

**Comment by JanMarvin** [comment] 2022-05-13 09:01
Like I've said, anything that helps reproducing the warning would be benefitial. If it can be reproduced with just the few lines and an artificial data set, that would give hints where to look at.

**Comment by dkoltg** [comment] 2022-05-13 09:21
Here some sample code:
```
tab_1 <- data.frame(date = c('8.05.2022', '9.05.2022', '10.05.2022', '11.05.2022', '12.05.2022'),
                    col_1 = c(4, 6, 20,'' , 3),
                    col_2 = c(1, 1,'' ,'' , 1),
                    col_3 = c(1,'' , 3, 13, 1),
                    col_4 = c('', 34, 3, 12, ''))

tab_2 <- data.frame(date = c('8.05.2022', '9.05.2022', '10.05.2022', '11.05.2022', '12.05.2022'),
                    col_1 = c(4, 6, 20,'' , 3),
                    col_2 = c(1, 1,'' ,'' , 1),
                    col_3 = c(1,'' , 3, 13, 1),
                    col_4 = c('', 2, 14, 9, 23),
                    col_5 = c(3,'' , 6, 13, 23),
                    col_6 = c(1, 4, 3,'' , 16))







## Create a new workbook
library(openxlsx)
wb <- createWorkbook("Example")

## Add some worksheets
addWorksheet(wb, "Tab 1")
addWorksheet(wb, "Tab 2")

hs1 <- createStyle(halign = "LEFT", wrapText = TRUE, valign = "TOP")

writeData(wb, "Tab 1", tab_1, colNames = T, rowNames = F,  headerStyle = hs1)
writeData(wb, "Tab 2", tab_2, colNames = T, rowNames = F,  headerStyle = hs1)
setColWidths(wb, "Tab 1",col=1,widths = "auto")
setColWidths(wb, "Tab 2",col=1,widths = "auto")
setColWidths(wb, "Tab 1",cols=2:4,widths=10)
setColWidths(wb, "Tab 2",cols=2:4,widths=11)
setColWidths(wb, "Tab 2",cols=5:6,widths=12)



## Freeze Panes
freezePane(wb, "Tab 1", firstRow = TRUE)
freezePane(wb, "Tab 2", firstRow = TRUE)


## Save workbook
saveWorkbook(wb, "~path/example.xlsx", overwrite = TRUE)
````

When I use a path in our drive, I get the warning...

**Comment by JanMarvin** [comment] 2022-05-14 20:15
Hi @dkoltg , I ran your example without an issue. No warning whatsoever.
```R
> packageVersion("openxlsx")
[1] ‘4.2.5’
```

**Comment by dkoltg** [comment] 2022-05-15 08:00
Hi, when I just run the code there is no issue, the warning appears as soon as I save the file on our drive. I work with version 4.2.3. Tried to update however get then in some troubles because of depending other packages that need to be in an older version...

**Comment by JanMarvin** [comment] 2022-05-15 08:48
Well 4.2.3 was released almost 1.5 years ago. Sorry but it's getting tough to remember what I had for lunch yesterday. Might be that we simply fixed it along the way. Let us know if you can reproduce it with the current release or the development branch :)

**Comment by dkoltg** [comment] 2022-05-15 08:52
I work in an IT-environment of an public administration which ends often in a mess regarding updates and so on. We will work with workbench solutotion in future (should be ready somewhen during summer) and I hope that such troubles will be easier to handle then...

**Comment by JanMarvin** [comment] 2022-05-15 08:56
Haha, well I know that feeling way to good. Closing this for now.

**Closed as completed by JanMarvin** 2022-05-15 08:56 UTC
Labels: invalid

**Comment by dkoltg** [comment] 2022-05-15 08:57
Thanks for your help :)

**Comment by JanMarvin** [comment] 2022-05-15 09:18
FYI your code in `openxlsx2`:

```R
# made it date and NA not '' will be shown as "#N/A" in Excel
tab_1 <- data.frame(date = as.Date(c('8.05.2022', '9.05.2022', '10.05.2022', '11.05.2022', '12.05.2022')),
                    col_1 = c(4, 6, 20, NA, 3),
                    col_2 = c(1, 1, NA ,NA , 1),
                    col_3 = c(1, NA, 3, 13, 1),
                    col_4 = c(NA, 34, 3, 12, NA))

tab_2 <- data.frame(date = as.Date(c('8.05.2022', '9.05.2022', '10.05.2022', '11.05.2022', '12.05.2022')),
                    col_1 = c(4, 6, 20, NA , 3),
                    col_2 = c(1, 1, NA ,NA , 1),
                    col_3 = c(1, NA, 3, 13, 1),
                    col_4 = c(NA, 2, 14, 9, 23),
                    col_5 = c(3, NA, 6, 13, 23),
                    col_6 = c(1, 4,3 ,NA , 16))

## Create a new workbook
library(openxlsx2)
wb <- wb_workbook("Full")

## Add some worksheets
wb$add_worksheet("File_1")
wb$add_worksheet("File_2")

## write the data
wb$add_data("File_1", tab_1, colNames = T, rowNames = F)
wb$add_data("File_2", tab_2, colNames = T, rowNames = F)

## create the header style
hs1 <- create_cell_style(wrapText = TRUE, horizontal = "left", vertical = "top")
wb$styles_mgr$add(hs1, "hs1")

## apply the header style
set_cell_style(wb, "File_1", "A1:E1", wb$styles_mgr$get_xf_id("hs1"))
set_cell_style(wb, "File_2", "A1:E1", wb$styles_mgr$get_xf_id("hs1"))

## set the column width
wb$set_col_widths("File_1",col=1,widths = "auto")
wb$set_col_widths("File_2",col=1,widths = "auto")
wb$set_col_widths("File_1",cols=2:4,widths=10)
wb$set_col_widths("File_2",cols=2:4,widths=11)
wb$set_col_widths("File_2",cols=5:6,widths=12)

## Freeze Panes
wb$freeze_pane("File_1", firstRow = TRUE)
wb$freeze_pane("File_2", firstRow = TRUE)

## save the file
wb$save("full.xlsx")
```

**Comment by dkoltg** [comment] 2022-05-15 09:41
Thanks
