### ISSUE TITLE
xlsx-files written by writexl::write_xlsx cannot be read by openxlsx::read.xlsx

### ISSUE THREAD

**Issue by Close-your-eyes** [ycphs/openxlsx#161] opened 2021-03-29 21:00 UTC
Expected Behavior

Reading an excel file with data on it into R.

Actual Behavior

A warning message appears:
Warning message: No data found on worksheet.

Reason:

I believe xlsx-files that were written previously with the write_xlsx from with writexl-package cannot be read. Something in the formatting may be wrong. So, this may be actually be a problem on the writexl-package but not only ...
Can this be fixed? So, that read.xlsx handles the putatively wrong formatting of xlsx files written with write_xlsx?

Solution, even though not satisfying:

Open the xlsx file with excel first and save again. Then read.xlsx can read it.

Steps to Reproduce the Problem

Save data to a xlsx file with writexl::write_xlsx.

Try to read it with openxlsx::read.xlsx.

Get an error.

Repair it by opening with excel. Alternatively though, it would be great if read.xlsx could handle it.

sessionInfo()

Version of openxlsx: 4.2.3
Version of R: 4.0.3
System: MacOS

example-file for reproduction:
[example.xlsx](https://github.com/ycphs/openxlsx/files/6224497/example.xlsx)

**Comment by JanMarvin** [comment] 2021-03-29 21:23
This is a duplicate of #112 (needs an implementation of `inlineStr`). It's looks similar to `t="str"`. Node `is`, would be `v` iirc. Everything is right with the file and our reader, we simply haven't implemented this type of string, most likely since no one needed it, requested it, or wanted to do it.

For reference it looks like this, but the import barks earlier, when no `v` node is found in the file.
```
<c r="A1" s="1" t="inlineStr">
  <is>
    <t>this</t>
  </is>
</c>
```

Edit: For reference see this [SO](https://stackoverflow.com/a/4740690). According to this `inlineStr` is the default for non formula inline strings.

**Comment by Fideldue** [comment] 2021-06-01 10:29
> This is a duplicate of #112 (needs an implementation of `inlineStr`). It's looks similar to `t="str"`. Node `is`, would be `v` iirc. Everything is right with the file and our reader, we simply haven't implemented this type of string, most likely since no one needed it, requested it, or wanted to do it.
> 
> For reference it looks like this, but the import barks earlier, when no `v` node is found in the file.
> 
> ```
> <c r="A1" s="1" t="inlineStr">
>   <is>
>     <t>this</t>
>   </is>
> </c>
> ```
> 
> Edit: For reference see this [SO](https://stackoverflow.com/a/4740690). According to this `inlineStr` is the default for non formula inline strings.

This helped me a lot to fiddle it myself into the `openxlsx` read function, Thanks!

**Comment by JanMarvin** [comment] 2021-06-01 11:13
Thank you for the reply. If you have something working, I'm sure a pull request would be more than welcomed! (I have a wip pull request for a new import function, that will make the implementation of this a lot easier, but it's still wip and I haven't found the time and motivation to pick it up again. Edit: the inlinestr patch is this: https://github.com/ycphs/openxlsx/pull/134/commits/db4bd6438a218be8276642b5155c9250d7835e87)

**Comment by JanMarvin** [comment] 2021-09-25 17:38
Basic support for inlineStr has been added to master a while ago. Though that could be improved. The current implementation looks for `<is><t>` and matching closing tags. Actually it should look for `<is>` only, since the formatting is identical to the sharedStrings one. Only that the inlineStr are ... well inline. But I'll leave that to someone else to implement.

**Closed as completed by JanMarvin** 2021-09-25 17:38 UTC
