### ISSUE TITLE
Percentage class on column with cell contaning 0 values

### ISSUE THREAD

**Issue by ale275** [ycphs/openxlsx#20] opened 2019-12-02 15:54 UTC
**Describe the bug**
Setting column class to `percentage` in a dataframe with multiple columns causes Excel to throw error on opening if the column itself contains one or more 0 values

**To Reproduce**
```
library(openxlsx)

test <- data.frame(
  val = c('alpha', 'beta', 'gamma', 'delta'),
  pcnt = c(0, 0.1, 0.2, 1)
  )
class(test$pcnt) <- "percentage"

wb <- createWorkbook()
addWorksheet(wb, "PCNT Test")
writeData(wb, sheet = "PCNT Test", x = test, startRow = 1, colNames = FALSE)

openXL(wb)
```

if val column is removed no corruption problem is detected by excel on file opening. Note on the error is "Number stored as text"

**Expected behavior**
No Warning on Excel opening and correct percentage render

**Screenshots**
_Wrong_
![wrong](https://user-images.githubusercontent.com/405331/69973566-01b70900-1524-11ea-8c29-cce80a6c71b8.JPG)
_Correct_
![correct](https://user-images.githubusercontent.com/405331/69973705-3aef7900-1524-11ea-8d40-0cd5067a1464.JPG)

**Desktop (please complete the following information):**
 - OS: Windows/Linux

**sessionInfo()**
`
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] openxlsx_4.1.3
`

**Comment by ycphs** [comment] 2019-12-05 20:13
Please close the issue, if the problem is solved.

**Closed as completed** 2019-12-30 22:44 UTC
Labels: fixed

**Comment by ale275** [comment] 2020-01-13 13:49
Sorry for the delay but I could not properly test

Confirm that is fixed

Thanks
Alessandro
