### ISSUE TITLE
SetColWidths not allowing to SaveWorkbook more than once (multiple files, same wb)

### ISSUE THREAD

**Issue by cavan-24hrcares** [ycphs/openxlsx#106] opened 2020-09-28 15:52 UTC
Hello, 

It looks like whenever I use the SetColWidths function, I am not able to run the SaveWorkbook function more than once for the same workbook. 

```r

# Saving two different excel files with the same workbook 

dude.wb = createWorkbook("cavan@24hrcares.com") 

addWorksheet(wb=dude.wb, sheetName = "Let Us See", gridLines = FALSE, tabColour = "deepskyblue")

writeData(wb=dude.wb, sheet="Let Us See", x=tibble(x=c("1st", "2nd")))

setColWidths(wb=dude.wb, sheet = "Let Us See", cols=c(1:5), widths = c(9,9,9,9,9))

saveWorkbook(wb=dude.wb, file="T:/Cavan/AR Model/Analysis/Checking Openxlsx.xlsx", overwrite=TRUE)
saveWorkbook(wb=dude.wb, file="T:/Cavan/AR Model/Analysis/Checking Openxlsx2.xlsx", overwrite=TRUE)

```

I was able to save the same wb to multiple files before the update, and now I cannot. Can you help? I am running this on Windows 10, R version 4.0.2

**Comment by JoshuaSturm** [comment] 2020-09-30 00:28
Thanks, I can replicate it.
The error seems to arise for any workbook name other than "wb". Must be a scoping issue again. Will be fixed in an upcoming PR; until then, try using "wb" as your workbook name.

Edit: renaming just removes the error. There's a related bug that's corrupting workbook attributes. Will be added to the PR.

**Closed as completed** 2020-10-26 21:06 UTC

**Comment by verena-e** [comment] 2022-01-10 13:23
Hello,

it looks like that I'm still observing a similar issue as described above:

When I try to store the same workbook in a second xlsx file using saveWorkbook() i get the warning 'NAs introduced by coercion' in R. When I open the file, it looks empty on the first glance but actually the data is in the file but the columns are hidden in excel and can be made visible by manually unhiding them in Excel.

```
#---------------- mini example

data(iris)
head(iris)

wb.test <- createWorkbook()

addWorksheet(wb.test, "Iris", zoom=80) 
writeDataTable(wb.test, "Iris", iris)
setColWidths(wb.test, "Iris", cols = c(1:ncol(iris)), widths = "auto")

saveWorkbook(wb.test, file = file.path(path,"test.xlsx"), overwrite=T, returnValue = T)
saveWorkbook(wb.test, file = file.path(path,"test2.xlsx"), overwrite=T, returnValue = T
```

Here the two files that are generated by the code above:
[test2.xlsx](https://github.com/ycphs/openxlsx/files/7839062/test2.xlsx)
[test.xlsx](https://github.com/ycphs/openxlsx/files/7839063/test.xlsx)

If I omit the setColWidths() function, saving into two files does work without any issues.

I'm using RVersion 4.0.2. via RStudio and openxslx Version 4.2.5.

Do you have any recommendation, how to solve this issue?

Thanks a lot!
Verena

**Comment by JanMarvin** [comment] 2022-01-10 16:49
The issue is likely caused by some overly aggressive cleanup in `saveWorkbook()`. Though I currently don't want to look into that further. I assume `copy.file()` is no feasible workaround?

**Comment by verena-e** [comment] 2022-01-11 07:13
Thanks for this hint. file.copy(), together with file.rename(), is a feasible work around.

**Comment by JanMarvin** [comment] 2022-01-11 10:48
Ah yes, typed the command from the top of my head. Sadly that is really just a workaround. We should be able to securely save the same workbook no matter how many times. I have opened a new issue from your comment. Maybe one day we'll fix it
